### ISSUE TITLE
Remove Duplicates

### ISSUE THREAD

**Issue by WYSNI** [djhn75/RNAEditor#16]
Hi David, 

I have a question about the "Remove PCR duplicates" step:

In your code, (see below) i think you just mark duplicates reads or not remove them because you just use the picard tool MarkDuplicates. The step rmdup is in comment .

I'm wrong?

#mark PCR duplicates
        #Helper.status("Remove Duplicates", self.rnaEdit.logFile,self.rnaEdit.textField)
        markedFile=self.rnaEdit.params.output+".noDup.bam"
        cmd=["java","-Xmx16G","-jar",self.rnaEdit.params.sourceDir + "picard-tools/MarkDuplicates.jar","INPUT=" + bamFile, "OUTPUT=" + markedFile, "METRICS_FILE="+self.rnaEdit.params.output+".pcr.metrics", "VALIDATION_STRINGENCY=LENIENT", "CREATE_INDEX=true"]
        Helper.proceedCommand("Remove PCR duplicates", cmd, bamFile, markedFile, self.rnaEdit)
        
        
        """if self.rnaEdit.params.paired == False:
            pysam.rmdup("-s",bamFile,markedFile)
        else:
            pysam.rmdup(bamFile,markedFile)
        #pysam.rmdup(bamFile,markedFile)
        if self.rnaEdit.params.paired == False:
            cmd = [self.rnaEdit.params.sourceDir + "samtools", "rmdup", "-s", bamFile, markedFile]
        else:
            cmd = [self.rnaEdit.params.sourceDir + "samtools", "rmdup", bamFile, markedFile]
        Helper.proceedCommand("Index Bam File", cmd, bamFile, markedFile, self.rnaEdit)
        
        
        Helper.status("index Bam", self.rnaEdit.logFile,self.rnaEdit.textField)
        pysam.index(markedFile)
        
        cmd = [self.rnaEdit.params.sourceDir + "samtools", "index", bamFile]
        Helper.proceedCommand("Index Bam File", cmd, bamFile, markedFile+".bai", self.rnaEdit)
        #return bamFile"""

Where did you remove duplicates reads?

Best,

WYSNI

**Comment by djhn75** [comment]
Dear WYSNI, you are totally right, the duplicates are simply marked, yet afterward those marked reads are ignored by GATK. 
Therefore duplicate reads cannot influence the SNP ratio.

We tested samtools rmdup too, therefore it is still in the code, but we recognised that GATK often crashes after we used samtools, because of incorrect formed files.

Thanks for your interest in RNAEditor

Best regards David
David John
Institute of Cardiovascular Regeneration
Theodor-Stern-Kai 7
D-60590 Frankfurt am Main
+49 69 6301 87952
John@med.uni-frankfurt.de <mailto:John@med.uni-frankfurt.de>

**Comment by djhn75** [comment]
Dear WYSNI, you are totally right, the duplicates are simply marked, yet afterward those marked reads are ignored by GATK. 
Therefore duplicate reads cannot influence the SNP ratio.

Here the code snippet:
```
#mark PCR duplicates
        #Helper.status("Remove Duplicates", self.rnaEdit.logFile,self.rnaEdit.textField)
        markedFile=self.rnaEdit.params.output+".noDup.bam"
        cmd=["java","-Xmx16G","-jar",self.rnaEdit.params.sourceDir + "picard-tools/MarkDuplicates.jar","INPUT=" + bamFile, "OUTPUT=" + markedFile, "METRICS_FILE="+self.rnaEdit.params.output+".pcr.metrics", "VALIDATION_STRINGENCY=LENIENT", "CREATE_INDEX=true"]
        Helper.proceedCommand("Remove PCR duplicates", cmd, bamFile, markedFile, self.rnaEdit)
        
```

We tested samtools rmdup too, therefore it is still in the code, but we recognised that GATK often crashes after we used samtools, because of incorrect formed files.

Thanks for your interest in RNAEditor

Best regards David
David John

**Comment by WYSNI** [comment]
Thanks a lot for your answer.

Best 
WYSNI
