### ISSUE TITLE
Testing dataset

### ISSUE THREAD

**Issue by mlebeur** [djhn75/RNAEditor#20]
Hi, Fisrtly thanks a lot for your work. I want to try RNAEditor on some clinical data and I went througth some difficulties to make RNAeditor work on my environment (ex: converting in python 3). So I was wondering if you have a small example dataset and the associated result to verify that nothing went wrong ?  
Once again that's a lot. Best regards. Manuel LEBEURRIER

**Comment by djhn75** [comment]
Dear Manuel, first of all thanks for using RNAEditor.
If you want a version RNAEditor which works for python3 i would recommend the fork of Zhinkun Wu (https://github.com/ZhikunWu/RNAEditor), who change some lines so RNAEditor should work for Python3. Although i cant guarantee that the code works completely fine, because i did all my testing with the software version which are mentioned in http://rnaeditor.uni-frankfurt.de/install.php

If you want a small dataset you could simply extract all reads that map to chromosome 1, with the samtools and afterwards rewrite the reads back to a bam file by samtools bam2fastq. This fastq file would the be small enough to use it as a test dataset.

Hope this helps

Best regards 

David John


David John, PhD
Institute of Cardiovascular Regeneration
Theodor-Stern-Kai 7
D-60590 Frankfurt am Main
+49 69 6301 87952
John@med.uni-frankfurt.de
